// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppPaintDbContext))]
    partial class AppPaintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Data.Models.DrawingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("DrawingTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "#F0F0F0",
                            CreatedAt = new DateTime(2025, 12, 7, 12, 39, 30, 918, DateTimeKind.Local).AddTicks(5998),
                            Height = 600.0,
                            IsTemplate = false,
                            Name = "Sample Template 1",
                            Width = 800.0
                        },
                        new
                        {
                            Id = 2,
                            BackgroundColor = "#E8F4F8",
                            CreatedAt = new DateTime(2025, 12, 7, 12, 39, 30, 918, DateTimeKind.Local).AddTicks(6000),
                            Height = 768.0,
                            IsTemplate = false,
                            Name = "Sample Template 2",
                            Width = 1024.0
                        });
                });

            modelBuilder.Entity("Data.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultCanvasHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultCanvasWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("DefaultFillColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultStrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultStrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 7, 12, 39, 30, 918, DateTimeKind.Local).AddTicks(5905),
                            DefaultBackgroundColor = "#FFFFFF",
                            DefaultCanvasHeight = 600.0,
                            DefaultCanvasWidth = 800.0,
                            DefaultFillColor = "#FFFFFF",
                            DefaultStrokeColor = "#000000",
                            DefaultStrokeThickness = 2.0,
                            IsActive = true,
                            Name = "Default Profile",
                            Theme = "System"
                        });
                });

            modelBuilder.Entity("Data.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FillColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFilled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PointsData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShapeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrokeStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Shapes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF0000",
                            CreatedAt = new DateTime(2025, 12, 7, 12, 39, 30, 918, DateTimeKind.Local).AddTicks(6014),
                            FillColor = "#FFCCCC",
                            IsFilled = true,
                            PointsData = "[{\"X\":100,\"Y\":100},{\"X\":300,\"Y\":250}]",
                            ShapeType = 1,
                            StrokeStyle = "Solid",
                            StrokeThickness = 3.0,
                            TemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#0000FF",
                            CreatedAt = new DateTime(2025, 12, 7, 12, 39, 30, 918, DateTimeKind.Local).AddTicks(6016),
                            IsFilled = false,
                            PointsData = "[{\"X\":500,\"Y\":300},{\"X\":600,\"Y\":300}]",
                            ShapeType = 3,
                            StrokeStyle = "Solid",
                            StrokeThickness = 2.0,
                            TemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#00FF00",
                            CreatedAt = new DateTime(2025, 12, 7, 12, 39, 30, 918, DateTimeKind.Local).AddTicks(6018),
                            IsFilled = false,
                            PointsData = "[{\"X\":50,\"Y\":50},{\"X\":400,\"Y\":400}]",
                            ShapeType = 0,
                            StrokeStyle = "Solid",
                            StrokeThickness = 5.0,
                            TemplateId = 2
                        });
                });

            modelBuilder.Entity("Data.Models.DrawingTemplate", b =>
                {
                    b.HasOne("Data.Models.Profile", "Profile")
                        .WithMany("DrawingTemplates")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Data.Models.Shape", b =>
                {
                    b.HasOne("Data.Models.DrawingTemplate", "Template")
                        .WithMany("Shapes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Data.Models.DrawingTemplate", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("Data.Models.Profile", b =>
                {
                    b.Navigation("DrawingTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
